# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e12826e38e9f52565f5e691ff46579e"
application_url = "https://service-excludeondiscountcode-web.vercel.app"
embedded = true
name = "ServiceExcludeondiscountcode"

[access_scopes]
scopes = "write_discounts,read_discounts"

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [ "https://service-excludeondiscountcode-web.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
